name: Generate contribution snake

on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%237c3aed&color_dots=%23ebedf0,%23cffafe,%2367e8f9,%2322d3ee,%230891b2
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23a78bfa&color_dots=%23161b22,%23312e81,%235b21b6,%237c3aed,%23c084fc

      - name: Publish snake to output branch
        uses: crazy-max/ghaction-github-pages@v5.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
